use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub enum Landuse {
    AnimalKeeping,
    Busstation,
    Cemetery,
    Churchyard,
    Construction,
    College,
    Commercial,
    CommunityCentre,
    Dam,
    Education,
    Farmyard,
    Garages,
    Grass,
    Healthcare,
    Hospital,
    Industrial,
    Kindergarten,
    Library,
    Military,
    Neighbourhood,
    Park,
    Parking,
    Pitch,
    Playground,
    Quarry,
    Quarter,
    Railway,
    RecreationGround,
    Religous,
    Residential,
    Retail,
    School,
    Stadium,
    Suburb,
    Themepark,
    Track,
    University,
    Zoo,
}
